version: '3.8'

services:
  redis-app:
    extends:
      file: docker-compose.base.yml
      service: redis-app
    ports:
      - 6379:6379

  paymaster-proxy-app:
    extends:
      file: docker-compose.base.yml
      service: paymaster-proxy-app
    labels:
      - 'traefik.http.routers.paymaster-proxy.rule=Host(`0.0.0.0`)'

    deploy:
      replicas: 3 # Simulate 3 pods

  reverse-proxy:
    image: traefik:v2.5
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
