version: '3.8'

services:
  redis-app:
    image: 'redis:latest'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 2s

  paymaster-proxy-app:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: paymaster-proxy
    environment:
      - PORT=7310
      - REDIS_URL=redis://redis-app:6379
    healthcheck:
      test: wget localhost:7310/healthz -q -O - > /dev/null 2>&1
    volumes:
      - ../../certs/extra-ca-certificates.crt:/usr/local/share/ca-certificates/extra-ca-certificates.crt
    depends_on:
      redis-app:
        condition: service_healthy
