version: '3.8'

services:
  redis-app:
    extends:
      file: docker-compose.base.yml
      service: redis-app
    ports:
      - 6379:6379

  paymaster-proxy-app:
    extends:
      file: docker-compose.base.yml
      service: paymaster-proxy-app
    ports:
      - '7310:7310'
